- name: Patch and update servers
  hosts: all
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Update apt packages
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == 'Ubuntu'
